# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-30 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='carts',
        ),
    ]
