# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-02 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Bookingdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
