# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-03 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Bookingdate',
        ),
    ]
