# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-03 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_checkoutdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='checkoutdate',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
