# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190403_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone_num',
            field=models.IntegerField(null=True),
        ),
    ]
