# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-03 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orders_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone_num',
        ),
    ]
