# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0012_remove_orders_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
        ),
    ]
