# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-14 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190329_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Opening_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
