# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Address',
            field=models.TextField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='Contact',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='Email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Opening_time',
            field=models.DateTimeField(),
        ),
    ]
