# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-17 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190417_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Address',
            new_name='Address_info',
        ),
    ]
