# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190417_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Contact',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
