# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-17 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190417_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Address_info',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Email',
        ),
    ]
