# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-09 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
