# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-09 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20190409_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_num',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
