# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-28 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hakunamatata', '0003_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
